version: '3'

volumes:
  postgres_data:
    driver: local

services:
  db:
    image: postgres:latest
    container_name: db.oxl
    volumes:
      - postgres_data:/var/lib/postgresql/db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432

  postgres:
    image: postgres:latest
    container_name: postgres.spd
    volumes:
      - ./db/backup.sql:/docker-entrypoint-initdb.d/kaycloakBackup.sql
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password

  keycloak:
    image: quay.io/keycloak/keycloak:legacy
    container_name: keycloak.spd
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: keycloak
      DB_USER: keycloak
      DB_PASSWORD: password
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: Pa55w0rd
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - postgres